### ISSUE TITLE
Adding YAML config for modifying specific things

### ISSUE THREAD

**Issue by TheJoshue** [hmes98318/Music-Disc#58]
**Describe the Issue/Feature**
It would be cool to see a config.yml where we could for example:
- disable commands like:
```yml
disabled-commands: [list, of, commands]
```
where we can even define ALL commands if we want to fully disable commands (to not get registered, if we need this for some reason or we don't want some commands to be enabled at all)
- there could also be a boolean option for this to disable all commands, not just specific ones
- there could be a list of user allowed commands which can contain none up to every defined (only the ones that bot registers)
- also could be a list of <ROLE> allowed commands, for example we want to create "DJ" role where we paste that role into config and only for them we specify some higher commands such as moving songs in the or whatever there is higher than just /play and /skip
```yml
allowed-commands:
- users:
- - play
- <ROLE_ID>: # this could be DJ or any other role
- - skip
- - move
- - ...
- <ANOTHER_ROLE_ID>: # there could be any amount of other roles
- - ...
# of course BOT_ADMINs have all commands allowed
```

**Why this issue to happened / feature is needed(give scenarios or use cases):**
I think this could be extremely useful especially about commands allowing because -- there is nowhere stated which commands are only allowed for privileged (admin) users, so bot admin can manage this in config and easily know on his mind which commands user can use (and not worry if there is something they didn't want players to use) and especially because when you enter "/" you can see all commands allowed from specific bot, so someone who loves to abuse stuff could find something that could be excessively used and for example cram up ram memory and machine where bot is hosted could crash (or bot only) -- this is just a banal example, the bot is REALLY good built and this is why even am writing these long suggestions, because i want it to be even better
The thing where you can dedicate more commands to specific roles so some users can be grant DJs on the server and they can use bot more to involve more people into it

There are a lot more but this is for now. Thanks for reading

**Screenshots**
/

**Version Information:**
/

**Additional context**
/
